# Generated by Django 2.0 on 2017-12-27 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tag_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='post',
            field=models.ForeignKey(default='.', on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
