# Generated by Django 2.0 on 2017-12-27 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20171227_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='the_post',
        ),
        migrations.AddField(
            model_name='tag',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
